"use client";

import { useState } from "react";

export default function LandingPage() {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle" | "submitting" | "done" | "error">("idle");

  const handleSubscribe = async () => {
    if (!email || !email.includes("@")) return;
    setStatus("submitting");
    try {
      const res = await fetch("/api/subscribers", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });
      setStatus(res.ok ? "done" : "error");
    } catch {
      setStatus("error");
    }
  };

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <div style={styles.accentBar} />

        <div style={styles.masthead}>
          <h1 style={styles.title}>台灣生成新聞</h1>
          <p style={styles.sub}>GENERATED BY WE TAIWAN</p>
        </div>

        <div style={styles.content}>
          <p style={styles.desc}>
            台湾現地メディアの報道をAIが毎朝日本語で要約。<br />
            為替・株価・天気から、日本企業の台湾進出事例、<br />
            ビジネストレンドまで。台湾ビジネスの「今」を1ページで。
          </p>

          <div style={styles.features}>
            <div style={styles.feature}>
              <span style={styles.featureIcon}>📰</span>
              <span>台湾8メディアのニュースをAI翻訳・要約</span>
            </div>
            <div style={styles.feature}>
              <span style={styles.featureIcon}>🏢</span>
              <span>日本企業の台湾進出 成功・苦戦事例</span>
            </div>
            <div style={styles.feature}>
              <span style={styles.featureIcon}>📊</span>
              <span>TWD/JPY・TAIEX・天気をリアルタイム表示</span>
            </div>
            <div style={styles.feature}>
              <span style={styles.featureIcon}>📧</span>
              <span>毎朝7時にメールでお届け</span>
            </div>
          </div>

          {status === "done" ? (
            <div style={styles.doneBox}>
              <p style={styles.doneText}>登録ありがとうございます！</p>
              <p style={styles.doneSub}>次号から配信されます。</p>
            </div>
          ) : (
            <div style={styles.subscribeBox}>
              <input
                type="email"
                placeholder="メールアドレスを入力"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSubscribe()}
                style={styles.input}
              />
              <button
                onClick={handleSubscribe}
                disabled={status === "submitting"}
                style={styles.btn}
              >
                {status === "submitting" ? "登録中..." : "無料で購読する"}
              </button>
              {status === "error" && (
                <p style={styles.errorText}>登録に失敗しました。もう一度お試しください。</p>
              )}
            </div>
          )}

          <a href="/latest" style={styles.previewLink}>
            最新号を読む →
          </a>
        </div>

        <div style={styles.footer}>
          <p style={styles.footerBrand}>台灣生成新聞</p>
          <p style={styles.footerDesc}>
            運営:{" "}
            <a href="https://wewewetw.jp/" style={styles.footerLink}>
              想像以上有限公司（We TAIWAN）
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#e2e2e2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Noto Sans JP', system-ui, sans-serif",
    padding: "24px 16px",
  },
  container: {
    maxWidth: 520,
    width: "100%",
    background: "#fff",
    borderRadius: 0,
    boxShadow: "0 2px 40px rgba(0,0,0,0.08)",
    overflow: "hidden",
  },
  accentBar: { height: 3, background: "#ff4200" },
  masthead: { padding: "36px 28px 0", textAlign: "center" as const },
  title: {
    fontFamily: "'Noto Serif TC', serif",
    fontWeight: 900,
    fontSize: "2rem",
    letterSpacing: "0.18em",
    marginRight: "-0.18em",
    color: "#060606",
  },
  sub: {
    marginTop: 6,
    fontFamily: "Montserrat, sans-serif",
    fontSize: "0.6rem",
    fontWeight: 600,
    letterSpacing: "0.14em",
    color: "#ff4200",
  },
  content: { padding: "28px 28px 20px" },
  desc: {
    fontSize: "0.88rem",
    lineHeight: 1.9,
    color: "#333",
    textAlign: "center" as const,
  },
  features: {
    margin: "24px 0",
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },
  feature: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: "0.82rem",
    color: "#444",
    padding: "8px 12px",
    background: "#f6f6f6",
    borderRadius: 4,
  },
  featureIcon: { fontSize: "1.1rem" },
  subscribeBox: { marginTop: 20, textAlign: "center" as const },
  input: {
    width: "100%",
    padding: "12px 16px",
    border: "1px solid #ddd",
    borderRadius: 4,
    fontSize: "0.88rem",
    outline: "none",
    marginBottom: 10,
  },
  btn: {
    width: "100%",
    padding: "13px 24px",
    background: "#060606",
    color: "#fff",
    border: "none",
    borderRadius: 4,
    fontSize: "0.88rem",
    fontWeight: 700,
    cursor: "pointer",
  },
  errorText: { color: "#ff4200", fontSize: "0.78rem", marginTop: 8 },
  doneBox: {
    marginTop: 20,
    padding: 20,
    background: "#f0fff0",
    borderRadius: 4,
    textAlign: "center" as const,
  },
  doneText: { fontWeight: 700, color: "#2e7d32" },
  doneSub: { fontSize: "0.82rem", color: "#555", marginTop: 4 },
  previewLink: {
    display: "block",
    marginTop: 20,
    textAlign: "center" as const,
    fontFamily: "Montserrat, sans-serif",
    fontSize: "0.75rem",
    fontWeight: 700,
    color: "#ff4200",
    textDecoration: "none",
  },
  footer: {
    padding: "20px 28px",
    borderTop: "1px solid #eaeaea",
    textAlign: "center" as const,
  },
  footerBrand: {
    fontFamily: "Montserrat, sans-serif",
    fontSize: "0.65rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "#888",
  },
  footerDesc: { fontSize: "0.62rem", color: "#b0b0b0", marginTop: 4 },
  footerLink: { color: "#b0b0b0", textDecoration: "none" },
};
